app/data/questions.yaml
=> yaml for Lab Design and Crowdsourcing Questionnaires

app/requirements.txt
=> Explicitly require Flask-Login==0.2.11.

.travis.yml
This fixes #16.
Note that we'll want to enable Travis CI on `GovLab/noi2` for this to do anything, though...
=> Run test suite on travis

app/factory.py, app/tests/test_models.py, app/tests/test_views.py
I'm adding more tests here, it's a work-in-progress (WIP).
=> More tests!

run.sh
* In `run.sh`, wait for postgres to be ready to accept connections
* This resolves #23
=> Wait for postgres to start before trying to start the app

app/translations/es_MX/LC_MESSAGES/messages.po
I'm still seeing TRANSLATE in the questionnaires. I don't know if it is because they are really missing or is it because Erika last pull does not appear in mine. It will be finished tomorrow.
=> Phrases done

app/tests/test_views.py, app/views.py
=> 404 on nonexistent user profiles.

app/templates/search.html, app/tests/test_views.py, app/views.py
This fixes #10 and adds a very basic smoke test for the search results page.
=> Make search results a GET request.

app/models.py, app/templates/activity.html, app/tests/test_models.py, app/tests/util.py, app/views.py, manage.py
This will add the "my profile progress" widget from the [mockup](https://projects.invisionapp.com/share/C745XG4QX#/screens/101003956) to the activity feed:
=> Add "my profile progress" functionality

app/forms.py
=> Use 'only' instead of 'exclude' for ModelForms.

app/templates/base.html
=> Remove base.html.

app/templates/my-profile.html
=> Remove commented-out geolocation code from my-profile.html

app/templates/activity.html
This fixes #58.
I've verified that this properly escapes usernames in user links.
=> Internationalize activity page.

app/forms.py, app/tests/test_views.py, app/views.py
=> Redirect user to registration step 3 if possible.

app/templates/security/_macros_new.html, app/templates/security/change_password.html, app/templates/security/forgot_password.html, app/templates/security/login_user.html, app/templates/security/reset_password.html
So far this includes changes to migrate the following pages:
* Login
* Forgot password
* Reset password
* Change password
=> Migrate more security-related pages to use fancy new UI

app/__init__.py, app/templates/register-step-3.html
This is a **rudimentary** UI migration. There's certain things we can't do right now because the current design doesn't require any JS, so no cool swiping stuff, and there's no blurry UI in the background either, as that will likely require its own separate work. Still, it's way, way better than sticking with the old UI.
=> Rudimentarily migrate registration step 3 to fancy new UI

app/translations/es_MX/LC_MESSAGES/messages.po
I just need to check with Maria the term "Data Governance".
=> Last transaltions

app/templates/__base_new__.html, app/templates/style-guide/base.html
=> Remove font-awesome from new ui.

app/__init__.py, app/config/config.yml, app/forms.py, app/static/sass/_bootstrap-modal.scss, app/templates/__base_ui__.html, app/templates/_macros.html, app/templates/activity.html, app/views.py
=> Migrate activity page to the new UI

app/views.py
=> Forward users from / to /activity if already logged in.

app/templates/activity.html, app/templates/user-profile.html
* Styling of "Most Connected" tab under `/activity`.
* Styling of "Most Complete" tab under `/activity`.
* Linking pencil icon to "edit profile" in user profile pages.
=> More new ui stuff

app/templates/feedback.html
=> Reskin feedback page to fancy new UI.

app/templates/_macros.html, app/templates/match-me.html, app/tests/test_views.py, app/views.py
This implements the new "Match Me" functionality.
=> Initial implementation of new 'Match Me' functionality

app/forms.py, app/templates/__base_ui__.html, app/templates/invite.html, app/tests/test_views.py, app/views.py
This fixes #164.
However, it still needs to be:
* properly styled (currently it just borrows styles from "edit profile", which themselves are temporary)
* given proper copy for the subject and body of the email
Note also that the functionality doesn't currently complain if the invitee is already in the network.
=> Implement 'Invite Someone'.

DEPLOYING.md, deploy.sh
=> Advise prod deploys to symlink production.yml.

app/static/sass/_activity.scss, app/static/sass/_match-me.scss, app/static/sass/_nav.scss, app/static/sass/_onboarding.scss, app/static/sass/_profile.scss
@toolness i removed all the flexbox related vendor prefixes i could find in the sass
=> removes flexbox vendor prefixes

.gitignore, app/data/deployments.yaml, app/static/js/pages/scroller.js, app/static/sass/_activity.scss, app/static/sass/_base.scss, app/static/sass/_network-viz.scss, app/static/sass/_profile.scss, app/templates/__base_ui__.html, app/templates/_macros.html, app/templates/_network-viz.html, app/templates/activity.html, app/templates/match-me.html, app/templates/network.html, app/templates/user-profile.html, development.yml
addresses issues #328 #327 #326 #324 #323 #322 #321
the fix for #322 is very rudimentary and may need a second iteration, due to general difficulties working with javascript described by https://github.com/GovLab/noi2/issues/330
will continue adding fixes for the remaining issues on this PR
=> [WIP] UX Fixes

app/data/deployments.yaml, app/forms.py, app/static/js/pages/scroller.js, app/templates/__base_ui__.html, app/templates/match-me.html, app/templates/search.html
fixes:
https://github.com/GovLab/noi2/issues/334
https://github.com/GovLab/noi2/issues/327
https://github.com/GovLab/noi2/issues/325
https://github.com/GovLab/noi2/issues/319
https://github.com/GovLab/noi2/issues/317
still in progress from UX list:
https://github.com/GovLab/noi2/issues/322 (js caching problem blocking see #330 )
https://github.com/GovLab/noi2/issues/318
https://github.com/GovLab/noi2/issues/335
=> [WIP] UX fixes 2
