GovLab/noi2

- app/config/config.yml
This fixes #6.
Since `DEBUG: False` is already specified in the sample production config given in the README, I figure the non-production one can default to `True`, though existing deploys should probably ensure they explicitly set `DEBUG: False` in their `local_config.yml` before this is merged!
> Default DEBUG to True for development.

- README.md
- app/tests/test_models.py
- nosetests.sh
This adds the simplest possible unit test infrastructure. While I think it may *technically* establish a connection to the database, unless I'm mistaken about how SQLAlchemy models work, it shouldn't actually *do* anything with that connection--I'd like to save setup/teardown of a test DB for a later PR.
> Add a trivial unit test suite.

- docker-compose.yml
Here's an example warning this suppresses:
> Warning: the mapping "conf/:/etc/nginx/conf.d/" in the volumes
> config for service "web" is ambiguous. In a future version of Docker,
> it will designate a "named" volume (see
> https://github.com/docker/docker/pull/14242). To prevent unexpected
> behaviour, change it to "./conf/:/etc/nginx/conf.d/"
This warning appears on Docker 1.8.2.
> Fix ambiguous docker volume warnings.

- README.md
This fixes #5 and generally updates the README to be more in sync with the latest version of Docker for OS X.
> Update README to reflect Docker Toolbox on OS X.

- app/factory.py
This is a potential fix for #33.
An alternative, perhaps more "proper" fix would be to not wrap flask-login flash message strings in `lazy_gettext` and to instead set `app.login_manager.localize_callback = gettext`. However, since I'm not entirely sure what such strings are, and since `unicode()` will just be a no-op if the argument is already unicode, I opted for this more expedient solution.
> Make login_required work again

- app/models.py
- app/templates/activity.html
- app/tests/test_models.py
- app/views.py
This adds a `get_most_complete_profiles` class method to `User`, which returns a list of the users with the most complete profiles.
It's based on the code for `User.nearest_neighbors`, but one concern I have about that method (and consequently this one) is that it doesn't seem to do any filtering of users by deployment... Shouldn't that be taken into account for all methods like this?
> Add "Most Complete Profiles" section to activity feed

- app/factory.py
- app/forms.py
Because of flask-security's lack of i18n, and because it's not possible to monkeypatch-in i18n support for its built-in form labels, we need to subclass every built-in form. Ugh!
Almost all this work was done by @talos in https://github.com/GovLab/noi2/commit/569eeb40ba1a7021f790c815117e0f9c282b2b4f, with the exception that I added a missing `password_length` validator to the `NOIRegisterForm`.
> Localize login/security form labels

- app/templates/feedback.html
- app/templates/my-profile.html
This uses the [`tojson`](http://flask.pocoo.org/docs/0.10/templating/#standard-filters) filter to properly escape `gettext` output when it's used within script tags.
So far the only places I know that need this are from examining f4113d7f5f8db81cf70299eecaa1e4177f5410a4:
* Within `feedback.html` (this page *is* potentially still broken due to #47, though). 
* Within `my-profile.html` (#44).
> Use tojson filter when gettext is used in script tags

- app/factory.py
- app/tests/test_views.py
> Make flask-security internationalize properly w/ interpolated strings.

- app/forms.py
- app/tests/test_views.py
This fixes #50. Also, since it's now actually possible for form validation to fail in the user profile page, I added a test for it.
> Require first and last name in user profile.

- app/models.py
- app/templates/activity.html
- app/tests/test_models.py
- fixtures/sample_users.json
* Add an outsider user to our fixtures to broadly test we search within
deployment
* Simplify `get_most_complete_profiles`, and have it search within deployment
* Update test to prove we're within deployment
* Update template to work with new method signature
> Only search within deployment for most complete profiles

- app/models.py
- app/templates/activity.html
- app/tests/test_models.py
- app/tests/test_views.py
- app/views.py
This PR is meant to bludgeon two birds with one stone:
1. Adding the following message to the activity stream when a user has fully completed the registration flow:
2. Directing users to complete the registration process if they haven't already (#49).
Technically, this could be split into two separate PRs, but it shouldn't be too hard to do as one.
Tasks left to do:
> Redirect user to registration flow and introduce them in the activity stream

- .gitignore
- app/factory.py
- app/requirements.txt
- app/sass.py
- app/static/sass/styles.scss
- app/templates/sass-test.html
- app/tests/test_sass.py
- app/views.py
- manage.py
- run.sh
Since @claudioccm's [CSS](https://github.com/claudioccm/noi-ui) is SASS-based, it'd be really nice if we could have the source SASS in this repository and easily iterate on it from here.
This PR adds [libsass-python](https://github.com/dahlia/libsass-python) to our `app` container and integrates SASS into our build process. 
**For development**, we use SASS middleware that regenerates the SASS on each request and gives us handy error feedback in our views like this:
> ![2015-10-02_12-56-32](https://cloud.githubusercontent.com/assets/124687/10252375/158b52f8-6905-11e5-90ac-f3d84fa9068a.png)
**For production**, I've added `manage.py build_sass`, which is executed as part of `run.sh`, so that our compiled SASS is served as static CSS in production.
We also compile our SASS as part of our …
> Add rudimentary SASS integration.

- app/static/sass/_nav.scss
- app/static/sass/_off-canvas.scss
- app/static/sass/styles.scss
Because the development and production paths to SASS files are located at [different paths](https://github.com/GovLab/noi2/blob/master/app/sass.py), this unfortunately makes referencing the static assets via relative paths problematic.
To get around this, we'll define a SASS variable called `$path-to-static` and use [interpolation syntax](https://web-design-weekly.com/snippets/url-as-a-sass-variable/) to reference our images and other static assets from our CSS.
> use a $path-to-static sass variable

- app/__init__.py
- app/static/vendor/bootstrap/js/alert.js
- app/templates/__base_new__.html
- app/templates/_macros.html
- app/templates/style-guide/alert.html
This does a few things:
* Replaces a janky `onclick` handler in our current alert code with [Bootstrap's alert plugin](http://getbootstrap.com/javascript/#alerts) (via its data API).
* Moves the alert-rendering code into a separate `_macros.html` file, so it's modularized and can be manually tested.
* Adds basic documentation and a manual test for the alert styling and dismissal logic under `/style-guide/alert`.
In general, I'd like to leverage jQuery plug-ins like this for our JS needs rather than writing our own from scratch, since they're well-tested in the wild and also deal with lots of edge cases (e.g. older browsers, accessibility issues) that we don't want to have to deal with the hard way.
> Use bootstrap's alert.js for fancy new UI alerts

- app/__init__.py
- app/static/sass/_activity.scss
- app/static/vendor/bootstrap/js/tab.js
- app/templates/style-guide/tab.html
Similar to #102 and #101, here we add Bootstrap's [tab plugin](http://getbootstrap.com/javascript/#tabs) and make a few minor modifications to `.b-contextual-nav` so the two are compatible with each other. A new `tab` style guide page can be used to manually test the integration.
> Make new UI's contextual nav work w/ Bootstrap's tab plugin

- app/templates/register-step-3.html
This helps with #115 and #116:
I'm still not a big fan of the way that "join" button looks, as it seems sorta "disabled", but it is indeed better than being completely unstyled!
> Improve registration step 3 styling

- app/forms.py
I think that [`flask.ext.babel.get_locale()`](https://pythonhosted.org/Flask-Babel/#flask.ext.babel.get_locale) is more appropriate in most cases, because it will ultimately take into account the current user's current locale. Which I think falls back to `BABEL_DEFAULT_LOCALE` if no other information is available (especially if we don't set our own [`localeselector`](https://pythonhosted.org/Flask-Babel/#flask.ext.babel.Babel.localeselector), which I think is currently the case).
For instance, even if `BABEL_DEFAULT_LOCALE` is `es`, if the current user decides to set their locale to `en`, they're going to want to see country/language names in English rather than the deployment's default of Spanish, right?
The only potential wrinkle here is if the form is instantiated outside of the …
> In forms, use flask.ext.babel.get_locale() instead of BABEL_DEFAULT_LOCALE

- app/templates/_macros.html
- app/templates/activity.html
- app/templates/style-guide/tab.html
This makes our tab-bar markup a bit more [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself) and also makes it easy for us to change what tab is active at template render time. This will hopefully make things easier for us when we need to render, for example, the nth step of a wizard interface that is embedded in a tab panel (which seems to be the case with our expertise questionnaires).
> Add render_tab_bar, render_tab_panel macros.

- app/static/sass/_components.scss
- app/static/sass/_find-innovator.scss
- app/templates/security/_macros_new.html
- app/templates/style-guide/find-innovator.html
- app/templates/style-guide/signup-basic-info.html
This does two things:
1. Gets rid of `.b-dropdown` and
2. Renames `.b-dropdown-alt` to `.b-dropdown`.
Note that `.b-dropdown` is now styled a bit funkily on security-related pages:
But @claudioccm will fix it!
> [design branch] unify .b-dropdown and .b-dropdown-alt

- app/forms.py
- app/templates/search-results.html
- app/templates/search.html
- app/tests/test_views.py
- app/views.py
~~This is a bit funky right now because the search form and results pages are currently two different views.~~ Both the search form and results are visible on the same page now.
Notes:
* I removed the "Contact all these people" button because it isn't in current mockups and it also seems to be broken.
* ~~We don't have any special styling for [chosen](https://harvesthq.github.io/chosen/) `<select>` elements so we're just using some temporary styling I added for now.~~ We've abandoned Chosen b/c it doesn't work w/ mobile.
* Also, using `b-button` for the form submit button yields a black button with dark grey text--very hard to read, so I changed the text to white via some temporary CSS.
This is what it looks like so far:
The multi-select fields are a bit ick. Also, the down-arrow on them …
> New UI for search and search results page

- app/static/sass/_match-me.scss
This fixes #153, but it does so by moving the user information *underneath* the profile picture instead of to the right side of it, because I wasn't sure how to make the fix via the flexbox model:
@claudioccm, if you have a better fix for this, feel free to revert this commit on the design branch and do it!
> Fix picture on 'match me' pages.

- app/templates/activity.html
- app/tests/test_views.py
- app/views.py
As mentioned in https://github.com/GovLab/noi2/pull/135#issuecomment-147752711, the activity page needs to be visible to logged-out users so that prospective users have some idea of what the value proposition of signing up to the site is.
UI changes to the logged-out version of this page:
* Changes to the topmost nav as mentioned in #135
* The "My Profile Progress" tab is gone
* There is no `mailto:` link on shared messages, as we don't want to expose users' email addresses so easily to spammers
> Make /activity publicly visible

- app/factory.py
- app/l10n.py
- app/templates/__base_new__.html
- app/tests/test_l10n.py
This lays a foundation for fixing #148 (and partially fixes it) by adding a simple [Babel `localeselector`](https://pythonhosted.org/Flask-Babel/#flask.ext.babel.Babel.localeselector) for the app that just compares the request's `Accept-Languages` header to the available translations.
This can be manually tested by using Firefox and going to "Options -> Content -> Languages -> Choose..." and adding "Spanish / Mexico [es-mx]" to the top of the list, and then reloading any page on the site, the language of which should change to Spanish. (Unfortunately, this is hard to do in other browsers because they don't seem to support explicitly setting es-mx.)
In the future, we can add some code to the `localeselector` that inspects the user's session and/or profile to choose a better language, along …
> Set locale based on Accept-Languages header

- app/__init__.py
- app/static/js/main.js
- app/static/js/tutorial.js
- app/static/sass/_tutorial.scss
- app/templates/__base_ui__.html
- app/templates/activity.html
- app/templates/style-guide/activity.html
- app/templates/style-guide/base.html
- app/templates/style-guide/tutorial.html
Notes:
* ~~There's frequently a one-pixel gap between the top arrow and the tutorial box content on my screen, which is really annoying.~~ Fixed!
* The turquoise color of the popup and the blue of the nav toolbar are very similar, so it's hard to see the popup arrow when it's pointing at the "Match Me" button.
* ~~If the window is resized, the tutorial popup's position doesn't adjust, so it's now pointing at potentially the wrong place.~~ Fixed!
* `_resetTutorial()` can be called from the browser console to reset the tutorial state on the server-side. Eventually it'd be nice to have a control for this from a settings page or somesuch.
* There's no ARIA markup for this at all and it's probably not particularly accessible right now.
> Initial implementation of tutorial popups.

- app/forms.py
- app/l10n.py
- app/static/js/main.js
- app/templates/main.html
- app/tests/test_l10n.py
- app/tests/test_views.py
- app/views.py
This fixes #148.
Right now it looks like a fairly gross select widget at the bottom of the homepage:
The gray discoloration is due to #141. The `es_MX` is apparently because that locale has a ['display_name`](http://babel.pocoo.org/docs/api/core/#babel.core.Locale.display_name) of `None`, so I'm falling back to the locale code. We should probably file a separate issue for that after this lands.
> Add a locale selector widget on the homepage.

- app/static/sass/_activity.scss
- app/static/vendor/jquery.jscroll.js
- app/templates/_activity_events.html
- app/templates/_activity_macros.html
- app/templates/activity.html
- app/tests/test_views.py
- app/views.py
This will fix #129.
Right now we're not using the auto-triggering feature of [jScroll](http://jscroll.com/) because the plugin doesn't work well in conjunction with our bootstrap tabs: specifically, if a tab other than the activity stream is active, jScroll will spam our server with ajax requests when the user scrolls to the bottom of the page.
So for now we just show a down-arrow that the user can click on to load more.
> Infinite scrolling

- app/data/questions.yaml
- app/static/sass/_profile.scss
- app/templates/_profile-questionnaire.html
- app/templates/about.html
- app/templates/register-step-3.html
- app/templates/user-profile.html
- app/tests/test_views.py
- app/views.py
This fixes #181.
During onboarding, this changes the onboarding innovation area intro text so it includes the area description:
Similarly, when users have started a questionnaire via their profile in an area that they don't have any reported skills in, they are shown the intro text:
However, this interstitial is skipped if the user has already answered any questions in the area.
> Display innovation area "intro text" when users first fill them out

- app/forms.py
- app/templates/search.html
- app/tests/test_views.py
- app/views.py
I *think* that's all that's needed to make the search more useful for now. It won't resolve all of #232, but AFAIK it's the smallest scope of work for a single PR that will still result in a coherent end-user experience.
> Improve search functionality

- README.md
- app/docker-quick/Dockerfile
- app/docker-quick/requirements.quick.txt
- docker-compose.yml
This is an attempt to make it easier to quickly iterate on dependencies for the `app` container (one of the recurring problems mentioned in #234).
Basically, `app/Dockerfile`, a.k.a. [thegovlab/noi2](https://hub.docker.com/r/thegovlab/noi2/) on Docker Hub, will be used as the "foundation" for the app container, but not all of it. A second, very lightweight container will sit atop it: this container normally will contain very few dependencies, if any, but it will be a place that devs can easily add or try out new dependencies, since the container will be so quick to rebuild.
As an example, the initial contents of this lightweight container in this PR add a very recent version of flask-admin directly from git, because it has new features (like CSV export) that aren't available in the …
> Add a lightweight docker container that inherits from the elephantine Docker Hub one

- README.md
- app/admin.py
- app/csp.py
- app/factory.py
- app/models.py
- app/templates/__base_ui__.html
- app/templates/admin/index.html
- app/templates/admin/master.html
- app/templates/admin/stats_index.html
- app/tests/test_admin.py
This PR adds an "Admin Panel" link to the user menu for qualified super-users:
Clicking on it takes the administrator to a page where they can list/edit users and export them to CSV:
It also provides functionality to get some (currently undocumented) statistics:
We use [flask-admin](http://flask-admin.readthedocs.org/) for this.
We also need a way of tracking which users are admins and which aren't. For now we'll just use the `ADMIN_UI_USERS` config list for this, where each entry is the email of an admin user.
This PR also adds a `is_admin()` method to the `User` model which essentially returns whether the user's email is in `ADMIN_UI_USERS`.
Note that since we don't actually support email validation at present, admins will have to manually verify that the users associated with the …
> Add admin panel

- app/tests/__init__.py
- app/tests/test_models.py
Hopefully this fixes #23 forever, by adding [package-level test setup](http://nose.readthedocs.org/en/latest/writing_tests.html#test-packages) that waits for postgres to be up.
Unfortunately, the tests seem to run a lot slower with postgres, which is a bummer.
> Always use postgres when running tests

- conf/noi-environments/noi-.conf
- deploy.sh
- docker-compose.yml
- production.yml
- run.sh
This switches us from using the manual setting of the `NOI_ENVIRONMENT` environment variable to determine whether or not to use production configuration over to a `production.yml` file, which is advised for [using Compose in production](https://docs.docker.com/compose/production/).
It also means that there won't be an annoying warning message about `NOI_ENVIRONMENT` being undefined every time docker-compose is run, which was introduced by c9a98f9caedc7b6769fddba2593dd4a2f7be94ca.
> Use production.yml instead of NOI_ENVIRONMENT

- app/noi1.py
- docker-compose.yml
- manage.sh
- nosetests.sh
- run.sh
This sets the [working directory](https://docs.docker.com/engine/reference/run/#workdir) of the `app` container to `/noi`, which does a few things:
* Improves dev/prod parity by having them both use the same working directory (previously, dev's working dir was `/` during execution while production's was `/noi`)
* Reduces dependency on hard-coding `/noi` as an absolute path, which could eventually make it easier to run the app outside of a Docker container (#234) if we want.
* Makes a number of scripts a bit less verbose.
* Reduces the need for workarounds that convert relative paths from the noi root dir on the docker host to paths on the container (e.g. 406cc97aab838f37ec77a12eb7c30e991b294dea).
> change working dir of app container to /noi

- app/models.py
- app/tests/test_models.py
- manage.py
This fixes #260.
Things to do:
> Allow users w/ emails to be deleted.

- app/__init__.py
- app/config/local_config.sample.yml
- app/docker-quick/requirements.quick.txt
- app/factory.py
- app/linkedin.py
- app/models.py
- app/static/js/pages/my-profile.js
- app/templates/_macros.html
- app/templates/my-profile.html
- app/templates/user-profile.html
- app/tests/test_linkedin.py
- app/tests/test_views.py
- app/views.py
- manage.py
> Add LinkedIn integration.

- .travis.yml
- app/linkedin.py
- app/tests/test_linkedin.py
- docker-compose.yml
- entrypoint.py
This fixes #275.
Note that existing deploys which don't already run as `root` on the host system will need to run the following from the root of their repository:
```bash
sudo chown -R $USER.$USER *
```
Or on OS X:
```bash
sudo chown -R $USER *
```
> Run docker commands under same uid as host.

- .gitignore
- .travis.yml
- README.md
- app/docker-quick/Dockerfile
- app/docker-quick/requirements.quick.txt
- app/tests/conftest.py
- app/tests/test_l10n.py
- app/tests/test_models.py
- app/tests/util.py
- nosetests.sh
- pytest.ini
I just noticed this [note to users](https://nose.readthedocs.org/en/latest/#note-to-users) in the nose docs:
> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2.
So we might want to migrate to py.test since it seems to have the closest feature parity with nose.
To do:
* It looks like nose is running our `db_test_request_context` helper function *three times*! Lame.
> Add pytest integration

- app/config/config.yml
- app/factory.py
- app/forms.py
- app/l10n.py
- app/templates/__base_new__.html
- app/templates/security/_menu_new.html
- app/templates/security/send_confirmation.html
- app/tests/test_views.py
- app/views.py
This is a prerequisite for Discourse integration (#280).
Note that confirmation once existed as a *required* activity for some NoI deploys, but was removed in 5edab516e82f0bb0e4dcde4b95bde4b23bfa7541. This PR brings back some of that code.
This PR also contains a workaround for https://github.com/mattupstate/flask-security/pull/489.
Stuff to do:
> Add support for optional email confirmation.
